micronaut:
  application:
    name: airbyte-workload-api-server
  executors:
    health:
      type: fixed
      n-threads: ${HEALTH_TASK_EXECUTOR_THREADS:10}
  security:
    authentication-provider-strategy: ALL
    enabled: ${API_AUTHORIZATION_ENABLED:false}
  server:
    port: 8007
    cors:
      enabled: true
      configurations:
        web:
          allowed-origins-regex:
            - ^.*$
    netty:
      aggregator:
        max-content-length: 52428800 # 50MB
      access-logger:
        enabled: ${HTTP_ACCESS_LOG_ENABLED:true}
    idle-timeout: ${HTTP_IDLE_TIMEOUT:5m}

endpoints:
  beans:
    enabled: true
    sensitive: false
  env:
    enabled: true
    sensitive: false
  health:
    enabled: true
    jdbc:
      enabled: false
    sensitive: false
  info:
    enabled: true
    sensitive: true
  loggers:
    enabled: true
    sensitive: false
  refresh:
    enabled: false
    sensitive: true
  routes:
    enabled: true
    sensitive: false
  threaddump:
    enabled: true
    sensitive: true

datasources:
  workload:
    connection-test-query: SELECT 1
    connection-timeout: 30000
    maximum-pool-size: ${CONFIG_DB_MAX_POOL_SIZE:10}
    minimum-idle: 0
    idle-timeout: 600000
    initialization-fail-timeout: -1 # Disable fail fast checking to avoid issues due to other pods not being started in time
    url: ${DATABASE_URL}
    driverClassName: org.postgresql.Driver
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    leak-detection-threshold: 40000 # This should be slightly higher than the connection-timeout setting but not too high to avoid false positives and negatives.

logger:
  levels:
    #   Uncomment to help resolve issues with conditional beans
    # io.micronaut.context.condition: DEBUG
#   Uncomment to help resolve issues with security beans
#      io.micronaut.security: DEBUG
#   Uncomment to help resolve issues with micronaut data
#      com.zaxxer.hikari.HikariConfig: DEBUG
#      com.zaxxer.hikari: TRACE
